apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  DB_HOST: {{ .Values.user.database.host | quote }}
  DB_PORT: {{ .Values.user.database.port | quote }}
  DB_NAME: {{ .Values.user.database.name | quote }}
