apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  DB_HOST: {{ .Values.auth.database.host | quote }}
  DB_PORT: {{ .Values.auth.database.port | quote }}
  DB_NAME: {{ .Values.auth.database.name | quote }}
