apiVersion: v1
kind: Secret
metadata:
  name: auth-service-db-credentials
type: Opaque
data:
  username: {{ .Values.auth.database.user | b64enc | quote }}
  password: {{ .Values.auth.database.password | b64enc | quote }}
