apiVersion: v1
kind: Secret
metadata:
  name: order-service-db-credentials
type: Opaque
data:
  username: {{ .Values.order.database.user | b64enc | quote }}
  password: {{ .Values.order.database.password | b64enc | quote }}
