apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://arch.homework/auth$request_uri"
    nginx.ingress.kubernetes.io/auth-method: "GET"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /users
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 8000
