apiVersion: v1
kind: Secret
metadata:
  name: user-service-db-credentials
type: Opaque
data:
  username: {{ .Values.user.database.user | b64enc | quote }}
  password: {{ .Values.user.database.password | b64enc | quote }}
