{
 "title": "HW05",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(sum by(method, path, le) (rate(http_response_duration_seconds_bucket{path!=\"/metrics\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(method, path, le) (rate(http_response_duration_seconds_bucket{path!=\"/metrics\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(method, path, le) (rate(http_response_duration_seconds_bucket{path!=\"/metrics\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency mid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(method, path, le) (rate(http_response_duration_seconds_bucket{path!=\"/metrics\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total{path!=\"/metrics\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "rate(http_errors_total[1m])\n", "legendFormat": "__auto" }
   ]
  }
 ]
}