apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-service-config
data:
  DB_HOST: {{ .Values.billing.database.host | quote }}
  DB_PORT: {{ .Values.billing.database.port | quote }}
  DB_NAME: {{ .Values.billing.database.name | quote }}
