apiVersion: v1
kind: Secret
metadata:
  name: billing-service-db-credentials
type: Opaque
data:
  username: {{ .Values.billing.database.user | b64enc | quote }}
  password: {{ .Values.billing.database.password | b64enc | quote }}
