apiVersion: v1
kind: Secret
metadata:
  name: warehouse-service-db-credentials
type: Opaque
data:
  username: {{ .Values.warehouse.database.user | b64enc | quote }}
  password: {{ .Values.warehouse.database.password | b64enc | quote }}
