apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
spec:
  replicas: {{ .Values.billing.replicaCount }}
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      initContainers:
        - name: billing-migrate
          image: "{{ .Values.billing.image.repository }}:{{ .Values.billing.image.tag }}"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "/app migrate up"]
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: DB_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: billing-service-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-service-db-credentials
                  key: password
      containers:
        - name: billing-service
          image: "{{ .Values.billing.image.repository }}:{{ .Values.billing.image.tag }}"
          imagePullPolicy: Always
          command: ["/app", "rest"]
          ports:
            - containerPort: 8001
          env:
            - name: HTTP_PORT
              value: "8001"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: DB_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: billing-service-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-service-db-credentials
                  key: password
