apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-rest-api-ingress
spec:
  ingressClassName: "nginx"
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-rest-api
                port:
                  number: 8000