apiVersion: batch/v1
kind: Job
metadata:
  name: go-rest-api-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c", "/app migrate up"]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: go-rest-api-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: go-rest-api-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: go-rest-api-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: go-rest-api-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: go-rest-api-db-credentials
                  key: password
      restartPolicy: OnFailure
