apiVersion: v1
kind: Secret
metadata:
  name: go-rest-api-db-credentials
type: Opaque
data:
  username: {{ .Values.database.user | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
