version: '3.1'

services:
  auth:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: auth
    restart: always
    ports:
      - '8001:8001'
    environment:
      - DB_HOST=postgres_auth
      - DB_PORT=5432
      - DB_NAME=otus
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - postgres_auth
  postgres_auth:
    image: postgres:15-alpine
    container_name: postgres_auth
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: otus
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres_auth_data: