apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  DB_HOST: {{ .Values.notification.database.host | quote }}
  DB_PORT: {{ .Values.notification.database.port | quote }}
  DB_NAME: {{ .Values.notification.database.name | quote }}
