apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-consumer
spec:
  replicas: {{ .Values.notification.replicaCount }}
  selector:
    matchLabels:
      app: notification-consumer
  template:
    metadata:
      labels:
        app: notification-consumer
    spec:
      containers:
        - name: notification-consumer
          image: "{{ .Values.notification.image.repository }}:{{ .Values.notification.image.tag }}"
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c", "/app consume order-created" ]
          ports:
            - containerPort: 8006
          env:
            - name: KAFKA_BROKER
              value: "kafka.order.svc.cluster.local:9092"
            - name: HTTP_PORT
              value: "8006"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: DB_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: notification-service-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-service-db-credentials
                  key: password
