apiVersion: v1
kind: Secret
metadata:
  name: notification-service-db-credentials
type: Opaque
data:
  username: {{ .Values.notification.database.user | b64enc | quote }}
  password: {{ .Values.notification.database.password | b64enc | quote }}
