services:
  consumer:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: consumer
    restart: always
    environment:
      - HTTP_PORT=8002
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=billing-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=billingdb
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=billing
    depends_on:
      - billing-postgres
      - kafka
    command: ["/app", "consume", "user-registered"]
  billing:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: billing
    restart: always
    ports:
      - '8002:8002'
    environment:
      - HTTP_PORT=8002
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=billing-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=billingdb
    depends_on:
      - migration
      - billing-postgres
    command: ["/app", "rest"]
  migration:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: migration
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=billing-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=billingdb
    depends_on:
      - billing-postgres
    command: [ "/app", "migrate", "up"]
  billing-postgres:
    image: postgres:15-alpine
    container_name: billing-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billingdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - '8090:8080'
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

volumes:
  postgres_data: