apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
spec:
  replicas: {{ .Values.warehouse.replicaCount }}
  selector:
    matchLabels:
      app: warehouse-service
  template:
    metadata:
      labels:
        app: warehouse-service
    spec:
      initContainers:
        - name: warehouse-migrate
          image: "{{ .Values.warehouse.image.repository }}:{{ .Values.warehouse.image.tag }}"
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c", "/app migrate up" ]
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: warehouse-service-config
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: warehouse-service-config
                  key: DB_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: warehouse-service-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: warehouse-service-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: warehouse-service-db-credentials
                  key: password
      containers:
        - name: warehouse-service
          image: "{{ .Values.warehouse.image.repository }}:{{ .Values.warehouse.image.tag }}"
          imagePullPolicy: Always
          command: [ "/app", "rest" ]
          ports:
            - containerPort: 8003
          env:
            - name: HTTP_PORT
              value: "8003"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: warehouse-service-config
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: warehouse-service-config
                  key: DB_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: warehouse-service-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: warehouse-service-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: warehouse-service-db-credentials
                  key: password
