apiVersion: v1
kind: Secret
metadata:
  name: delivery-service-db-credentials
type: Opaque
data:
  username: {{ .Values.delivery.database.user | b64enc | quote }}
  password: {{ .Values.delivery.database.password | b64enc | quote }}
